In [1]:
import pandas as pd
from datasets import load_dataset

In [2]:
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

In [3]:
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

# Data Cleanup

Converted the job_posted_date column from string format to datetime format.

In [4]:
de_jobs = df[df['job_country'] == 'Germany']
de_jobs

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
34,Data Analyst,Data Analyst als Marketing Manager Automation ...,"Erlangen, Germany",via Central Illinois Proud Jobs,Full-time,False,Germany,2023-02-23 13:31:28,True,False,Germany,NaN,NaN,NaN,DEFACTO GmbH,['sap'],{'analyst_tools': ['sap']}
64,Senior Data Analyst,Senior Data Analyst,"Berlin, Germany",via BeBee,Full-time,False,Germany,2023-11-25 13:13:39,True,False,Germany,NaN,NaN,NaN,Stepstone GmbH,NaN,NaN
78,Senior Data Scientist,Senior Data Expert,"Berlin, Germany",via Jobs Trabajo.org,Full-time,False,Germany,2023-10-27 13:13:25,False,False,Germany,NaN,NaN,NaN,SIXT Germany,"['sql', 'excel', 'looker', 'sap']","{'analyst_tools': ['excel', 'looker', 'sap'], ..."
104,Software Engineer,Senior Software Engineer - Metadata,"Berlin, Germany",via Snowflake Careers,Full-time,False,Germany,2023-10-27 13:13:54,False,False,Germany,NaN,NaN,NaN,Snowflake,"['c++', 'java', 'snowflake']","{'cloud': ['snowflake'], 'programming': ['c++'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785728,Senior Data Scientist,"Senior Data Scientist, Operations Research",Jerman,melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,Wolt Oy,"['python', 'sql']","{'programming': ['python', 'sql']}"
785729,Data Engineer,Data Engineer Marketing Intelligence,Jerman,melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,IU Internationale Hochschule,NaN,NaN
785732,Data Engineer,Data Engineer (f/m/d),"Heidelberg, Jerman",melalui Top County Careers,Pekerjaan tetap,False,Germany,2023-03-13 06:18:59,False,False,Germany,NaN,NaN,NaN,Heidelberg Materials,"['python', 'c#', 'java', 'scala', 'sql', 'post...","{'cloud': ['azure', 'databricks'], 'databases'..."
785735,Senior Data Engineer,Senior Data Engineer,"Berlin, Jerman",melalui Top County Careers,Pekerjaan tetap,False,Germany,2023-03-13 06:19:07,False,False,Germany,NaN,NaN,NaN,Pure App,"['sql', 'python', 'bigquery', 'aws', 'airflow'...","{'cloud': ['bigquery', 'aws'], 'libraries': ['..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."

# Germany Data

Filtered the dataset to include only jobs located in Germany.

In [5]:
job_counts = (
    de_jobs
    .groupby('job_title_short')
    .size()
    .sort_values(ascending=False)
)

job_counts

job_title_short
Data Analyst                 7131
Data Scientist               6745
Data Engineer                6675
Senior Data Engineer         2041
Senior Data Scientist        1737
Senior Data Analyst          1216
Business Analyst              817
Software Engineer             741
Machine Learning Engineer     402
Cloud Engineer                189
dtype: int64

# Job Counts

Shows the number of job postings for each job title in Germany.

In [6]:
salary_stats = (
    de_jobs
    .groupby('job_title_short')['salary_year_avg']
    .agg(['median', 'min', 'max', 'count'])
    .sort_values(by='median', ascending=False)
)

salary_stats

                             median      min       max  count
job_title_short
Senior Data Scientist      157500.0  80850.0  224500.0     21
Data Engineer              147500.0  56700.0  200000.0     39
Senior Data Engineer       147500.0  72900.0  155500.0     26
Data Scientist             131560.0  56700.0  192000.0     41
Senior Data Analyst        111175.0  57600.0  119400.0     15
Data Analyst               103750.0  51014.0  200000.0     48
Cloud Engineer              89100.0  80850.0  200000.0      7
Business Analyst            89100.0  29900.0  126000.0     11
Machine Learning Engineer   89100.0  44418.5  224500.0     39
Software Engineer           84975.0  56700.0  177283.0     10

# Salary Statistics

Displays median salary, minimum salary, maximum salary, and sample count for each role.

# Findings

1. The most common data roles in Germany are Data Analyst, Data Scientist, and Data Engineer.

2. Senior Data Scientist roles showed the highest median salary in this dataset.

3. Some job titles have very small sample sizes, so their salary statistics should be interpreted carefully.

4. Data Analyst, Data Scientist, and Data Engineer positions appear to make up a large portion of the German data job market.